Settings: Fix NullPointerException in TrickyStoreAppSettings
When launching TrickyStoreAppSettings, a fatal crash occurs due to a NullPointerException
in PreferenceFragmentCompat$DividerDecoration.setDivider().

Since this fragment overrides onCreateView() to return a pure ComposeView instead of
inflating a traditional preferences XML layout, the internal RecyclerView remains null.
The base fragment attempts to invoke invalidateItemDecorations() on this non-existent
RecyclerView during onViewCreated(), causing the crash.

Fix this by overriding setDivider() and setDividerHeight() to safely bypass the base
implementation, as dividers are handled natively within the Jetpack Compose layout.

Logcat:
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.invalidateItemDecorations()' on a null object reference
    at androidx.preference.PreferenceFragmentCompat$DividerDecoration.setDivider(PreferenceFragmentCompat.java:909)
    at androidx.preference.PreferenceFragmentCompat.setDivider(PreferenceFragmentCompat.java:247)
    at com.android.settingslib.widget.SettingsBasePreferenceFragment.onViewCreated(SettingsBasePreferenceFragment.kt:47)

Change-Id: I6b9f922c2c22d5d9767b587f4fe0133a30a6ece8
Signed-off-by: klozz <carlosj@klozz.dev>